SplitterArguments: 
  chunk_size: 2000
  chunk_overlap: 100


#
# temperature: Measure of creativity, less means more direct the response
# max_tokens: defines the maximum number of tokens to be generated WRT a prompt
ModelArguments:
  temperature: 0.9
  max_tokens: 500 

Vector_dbArguments:
  k: None
  num_of_cells: None
  nprobe: None