artifacts_root: artifacts

data_Loader: None

vectorization:
  root_dir: artifacts/vector_db
  encoder_name: all-mpnet-base-v2
  model_ckpt: None
  data_path: None

model:
  model_name: gpt-3.5-turbo-instruct




